### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iefraim** [vydimitrov/react-countdown-circle-timer#232]
I am getting this error message:
`index.module.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at j (index.module.js:1:1)
    at S (index.module.js:1:1)
    at D (index.module.js:1:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)`

**Comment by vydimitrov** [comment]
@iefraim, this really does not help. Can you prep a reproduction demo so I can take a look on it?

**Comment by iefraim** [comment]
sorry
